using System.Collections.Generic;
using UnityEngine;

namespace Oculus.Interaction
{
    public class CustomGrabbable : PointableElement, IGrabbable
    {
        [SerializeField, Interface(typeof(ITransformer))]
        [Optional(OptionalAttribute.Flag.AutoGenerated)]
        private MonoBehaviour _oneGrabTransformerLeft = null;

        [SerializeField, Interface(typeof(ITransformer))]
        [Optional(OptionalAttribute.Flag.AutoGenerated)]
        private MonoBehaviour _oneGrabTransformerRight = null;

        [SerializeField, Interface(typeof(ITransformer)), Optional]
        private MonoBehaviour _twoGrabTransformer = null;

        [Tooltip("The target transform of the Grabbable. If unassigned, " +
            "the transform of this GameObject will be used.")]
        [SerializeField]
        [Optional(OptionalAttribute.Flag.AutoGenerated)]
        private Transform _targetTransform;

        [SerializeField]
        private int _maxGrabPoints = -1;

        public int MaxGrabPoints
        {
            get
            {
                return _maxGrabPoints;
            }
            set
            {
                _maxGrabPoints = value;
            }
        }

        public Transform Transform => _targetTransform;
        public List<Pose> GrabPoints => _selectingPoints;

        private ITransformer _activeTransformer = null;
        private ITransformer OneGrabTransformerLeft;
        private ITransformer OneGrabTransformerRight;
        private ITransformer TwoGrabTransformer;

        protected override void Awake()
        {
            base.Awake();
            OneGrabTransformerLeft = _oneGrabTransformerLeft as ITransformer;
            OneGrabTransformerRight = _oneGrabTransformerRight as ITransformer;
            TwoGrabTransformer = _twoGrabTransformer as ITransformer;
        }

        protected override void Start()
        {
            this.BeginStart(ref _started, () => base.Start());

            if (_targetTransform == null)
            {
                _targetTransform = transform;
            }

            if (_oneGrabTransformerLeft != null)
            {
                this.AssertField(OneGrabTransformerLeft, nameof(OneGrabTransformerLeft));
                OneGrabTransformerLeft.Initialize(this);
            }

            if (_oneGrabTransformerRight != null)
            {
                this.AssertField(OneGrabTransformerRight, nameof(OneGrabTransformerRight));
                OneGrabTransformerRight.Initialize(this);
            }

            if (_twoGrabTransformer != null)
            {
                this.AssertField(TwoGrabTransformer, nameof(TwoGrabTransformer));
                TwoGrabTransformer.Initialize(this);
            }

            // Create a default if no transformers assigned
            if (OneGrabTransformerLeft == null && OneGrabTransformerRight == null &&
                TwoGrabTransformer == null)
            {
                OneGrabFreeTransformer defaultTransformer = gameObject.AddComponent<OneGrabFreeTransformer>();
                _oneGrabTransformerRight = defaultTransformer;
                OneGrabTransformerRight = defaultTransformer;
                OneGrabTransformerRight.Initialize(this);
            }

            this.EndStart(ref _started);
        }

        public override void ProcessPointerEvent(PointerEvent evt)
        {
            switch (evt.Type)
            {
                case PointerEventType.Select:
                    EndTransform();
                    break;
                case PointerEventType.Unselect:
                    EndTransform();
                    break;
                case PointerEventType.Cancel:
                    EndTransform();
                    break;
            }


            base.ProcessPointerEvent(evt);

            bool isRightTransformer = false;

            if(evt.Data.ToString().Contains("Ray")){
                if ((evt.Data as RayInteractor).gameObject.ToString().Contains("Right")){
                    isRightTransformer = true;
                }
            } else {
                if ((evt.Data as GrabInteractor).gameObject.ToString().Contains("Right")){
                    isRightTransformer = true;
                }
            }

            switch (evt.Type)
            {
                case PointerEventType.Select:
                    BeginTransform(isRightTransformer);
                    break;
                case PointerEventType.Unselect:
                    BeginTransform(!isRightTransformer);
                    break;
                case PointerEventType.Move:
                    UpdateTransform();
                    break;
            }
        }

        // Whenever we change the number of grab points, we save the
        // current transform data
        private void BeginTransform(bool isRightTransformer)
        {
            // End the transform on any existing transformer before we
            // begin the new one
            EndTransform();

            int useGrabPoints = _selectingPoints.Count;
            if (_maxGrabPoints != -1)
            {
                useGrabPoints = Mathf.Min(useGrabPoints, _maxGrabPoints);
            }

            switch (useGrabPoints)
            {
                case 1:
                    _activeTransformer = isRightTransformer ? OneGrabTransformerRight : OneGrabTransformerLeft;
                    break;
                case 2:
                    _activeTransformer = TwoGrabTransformer;
                    break;
                default:
                    _activeTransformer = null;
                    break;
            }

            if (_activeTransformer == null)
            {
                return;
            }

            _activeTransformer.BeginTransform();
        }

        private void UpdateTransform()
        {
            if (_activeTransformer == null)
            {
                return;
            }

            _activeTransformer.UpdateTransform();
        }

        private void EndTransform()
        {
            if (_activeTransformer == null)
            {
                return;
            }
            _activeTransformer.EndTransform();
            _activeTransformer = null;
        }

        protected override void OnDisable()
        {
            if (_started)
            {
                EndTransform();
            }

            base.OnDisable();
        }

        #region Inject

        public void InjectOptionalOneGrabTransformerLeft(ITransformer transformer)
        {
            _oneGrabTransformerLeft = transformer as MonoBehaviour;
            OneGrabTransformerLeft = transformer;
        }

        public void InjectOptionalOneGrabTransformerRight(ITransformer transformer)
        {
            _oneGrabTransformerRight = transformer as MonoBehaviour;
            OneGrabTransformerRight = transformer;
        }

        public void InjectOptionalTwoGrabTransformer(ITransformer transformer)
        {
            _twoGrabTransformer = transformer as MonoBehaviour;
            TwoGrabTransformer = transformer;
        }

        public void InjectOptionalTargetTransform(Transform targetTransform)
        {
            _targetTransform = targetTransform;
        }

        #endregion
    }
}
